# Generated by Django 4.2.9 on 2025-12-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='shops/')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('remark', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
